# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 533)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.intro = QtWidgets.QLabel(self.centralwidget)
        self.intro.setObjectName("intro")
        self.verticalLayout.addWidget(self.intro)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 705, 305))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ans6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans6.setObjectName("ans6")
        self.gridLayout_2.addWidget(self.ans6, 7, 1, 1, 1)
        self.ans5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans5.setObjectName("ans5")
        self.gridLayout_2.addWidget(self.ans5, 6, 1, 1, 1)
        self.game9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game9.setObjectName("game9")
        self.gridLayout_2.addWidget(self.game9, 10, 0, 1, 1)
        self.game2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game2.setObjectName("game2")
        self.gridLayout_2.addWidget(self.game2, 3, 0, 1, 1)
        self.ans9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans9.setObjectName("ans9")
        self.gridLayout_2.addWidget(self.ans9, 10, 1, 1, 1)
        self.game5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game5.setObjectName("game5")
        self.gridLayout_2.addWidget(self.game5, 6, 0, 1, 1)
        self.game1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game1.setObjectName("game1")
        self.gridLayout_2.addWidget(self.game1, 2, 0, 1, 1)
        self.ans8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans8.setObjectName("ans8")
        self.gridLayout_2.addWidget(self.ans8, 9, 1, 1, 1)
        self.ans2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans2.setObjectName("ans2")
        self.gridLayout_2.addWidget(self.ans2, 3, 1, 1, 1)
        self.game6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game6.setObjectName("game6")
        self.gridLayout_2.addWidget(self.game6, 7, 0, 1, 1)
        self.game3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game3.setObjectName("game3")
        self.gridLayout_2.addWidget(self.game3, 4, 0, 1, 1)
        self.game8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game8.setObjectName("game8")
        self.gridLayout_2.addWidget(self.game8, 9, 0, 1, 1)
        self.game0 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game0.setObjectName("game0")
        self.gridLayout_2.addWidget(self.game0, 0, 0, 1, 1)
        self.ans3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans3.setObjectName("ans3")
        self.gridLayout_2.addWidget(self.ans3, 4, 1, 1, 1)
        self.ans7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans7.setObjectName("ans7")
        self.gridLayout_2.addWidget(self.ans7, 8, 1, 1, 1)
        self.ans1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans1.setObjectName("ans1")
        self.gridLayout_2.addWidget(self.ans1, 2, 1, 1, 1)
        self.game7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game7.setObjectName("game7")
        self.gridLayout_2.addWidget(self.game7, 8, 0, 1, 1)
        self.ans4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans4.setObjectName("ans4")
        self.gridLayout_2.addWidget(self.ans4, 5, 1, 1, 1)
        self.game4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game4.setObjectName("game4")
        self.gridLayout_2.addWidget(self.game4, 5, 0, 1, 1)
        self.ans0 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans0.setObjectName("ans0")
        self.gridLayout_2.addWidget(self.ans0, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.points = QtWidgets.QLCDNumber(self.centralwidget)
        self.points.setObjectName("points")
        self.verticalLayout.addWidget(self.points)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout.addWidget(self.clearButton)
        self.restartButton = QtWidgets.QPushButton(self.centralwidget)
        self.restartButton.setObjectName("restartButton")
        self.verticalLayout.addWidget(self.restartButton)
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setObjectName("submitButton")
        self.verticalLayout.addWidget(self.submitButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.intro.setText(_translate("MainWindow", "START USING YOUR INSTINCTS"))
        self.game9.setText(_translate("MainWindow", "TextLabel"))
        self.game2.setText(_translate("MainWindow", "TextLabel"))
        self.game5.setText(_translate("MainWindow", "TextLabel"))
        self.game1.setText(_translate("MainWindow", "TextLabel"))
        self.game6.setText(_translate("MainWindow", "TextLabel"))
        self.game3.setText(_translate("MainWindow", "TextLabel"))
        self.game8.setText(_translate("MainWindow", "TextLabel"))
        self.game0.setText(_translate("MainWindow", "Game of Thrones"))
        self.game7.setText(_translate("MainWindow", "TextLabel"))
        self.game4.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "YOUR SCORE"))
        self.clearButton.setText(_translate("MainWindow", "RESET"))
        self.restartButton.setText(_translate("MainWindow", "RESTART"))
        self.submitButton.setText(_translate("MainWindow", "SUBMIT"))

        self.restartButton.clicked.connect(MainWindow.restart)
        self.submitButton.clicked.connect(MainWindow.submit)
        self.clearButton.clicked.connect(MainWindow.clear)


